manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  defaults:
    remote: ncs
  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v1.9.0
      import: true
  self:
    path: application
