

OBJECTS=main.o \
    asinine/src/asn1-oid.o \
	asinine/src/asn1-parser.o \
	asinine/src/asn1-types.o \
	asinine/src/x509-name.o \
	asinine/src/x509-path.o \
	asinine/src/x509-pubkey.o \
	asinine/src/x509.o


